name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Test
      env: # Or as an environment variable
        OMDB_URL: ${{ secrets.OMDB_URL }}
        OMDB_KEY: ${{ secrets.OMDB_KEY }}
      run: go test -v .

    - name: Build
      run: go build -v .


